const fs=require('fs'),path=require('path'),today=new Date().toISOString().slice(0,10),slug=today;
const feed=JSON.parse(fs.readFileSync(path.join(__dirname,'..','feed.json'),'utf8'));
if(feed.posts.find(p=>p.slug===slug)){console.log('Exists');process.exit(0)}
const articles=[
{title:'不用花一分钱！用废纸箱做出能用的书架——家里纸箱别扔了',tag:'废品改造',intro:'快递纸箱堆在角落里占地方？扔掉之前看完这个——你花几百块买的置物架，用废纸箱就能做出来。不需要任何专业技能，只要一把美工刀和一瓶胶水。',sections:[{title:'📦 材料和工具',body:'主材料：快递纸箱（越多越好，建议至少攒5-8个同规格的）。辅助材料：白乳胶（十块钱一大瓶）、美纹纸胶带（固定用）。工具：美工刀、直尺、铅笔。总成本：不到15块钱。之前买过一个类似的纸板书架花了200多，自己做完感觉血亏。'},{title:'🔪 制作步骤',body:'1.把所有纸箱拆开摊平，选一面干净的面做外表。2.用直尺和铅笔画好要切割的线——切歪了会很难看，多量几次。3.美工刀沿着线切开，纸板厚的话分两次切不要一次切透。4.用胶水把纸板粘合成想要的形状——书架/收纳盒/笔筒/手机支架都可以。5.美纹纸胶带固定等胶水干透（至少4小时）。6.外面可以贴喜欢的包装纸或者用丙烯颜料涂色。做出来的成品质感比买的差一点，但用起来一模一样——关键是那种"自己做出来的"成就感。'},{title:'💡 更多纸箱改造创意',body:'小纸箱→手机/平板支架（比买的稳还不用充电）。中号纸箱→桌面收纳盒（分隔放文具充电线杂物）。大号纸箱→猫窝（猫咪超爱纸箱不用买昂贵的猫窝了）。长条纸箱→鞋架。不需要手艺多好——纸箱不值钱，做坏了重新来，成本几乎为零。做多了你会发现最好的家具有时候不在宜家，在垃圾桶旁边。'}]},
{title:'从零开始做一张实木桌子：没有木工经验也能上手',tag:'木工DIY',intro:'一张实木桌子在淘宝卖2000-5000。自己做的成本不到500，而且你能完全按照自己想要的尺寸和颜色来做。不需要专业木工房——在阳台上就能干。',sections:[{title:'🪵 选材和买材料',body:'第一次做桌子建议用松木：便宜、软好加工、容错率高。去建材市场买规格材（已经刨好的不用自己刨），尺寸让店家帮你切好。一张1.2米×0.6米的桌子需要：桌面板（2-3块木板拼接）约200元、桌腿4根约80元、横撑2根约40元。工具：手电钻（100块够用）、木螺丝、砂纸（80目+180目）、木蜡油（一瓶30）。总预算500以内。没有电钻可以问朋友借或者去工具租赁店。'},{title:'🔨 组装步骤',body:'1.砂纸打磨——80目粗磨去掉毛刺，180目细磨表面光滑。打磨比你想的更花时间，别急。2.桌面板拼好——板子并排放好底下用两根横木条把它们固定在一起。3.装上桌腿——先固定横撑在桌腿之间让结构稳定，再把整个腿架固定在桌面底下。4.涂木蜡油——保护木材+让木纹显出来。涂完等干再涂一遍效果更好。5.干了就可以用了。一张自己做的桌子放在家里，比所有买来的家具都有故事。'},{title:'⚠️ 新手避坑',body:'不要一上来就做很复杂的设计——先做一张最简单的。不要买太硬的木材（橡木硬到你怀疑人生）——第一次用松木。拼接的时候所有螺丝孔先打引导孔（用小号钻头钻一下），不然木板会裂开。不要纠结完美——手工活第一件肯定有瑕疵，第二个就会好很多。'}]},
{title:'手搓一个蓝牙音箱：用旧手机零件+淘宝配件，成本50块音质不输200的',tag:'电子DIY',intro:'家里淘汰的旧手机别扔——拆开里面有喇叭、有电池、有蓝牙模块。再加几个淘宝配件，就能组装出一个音质还不错的蓝牙音箱。关键不是省钱，是\"这东西是我自己做的\"。',sections:[{title:'🔌 需要的材料和工具',body:'核心配件（淘宝都有）：蓝牙功放板（15-30元带蓝牙5.0的就行）、3W或5W喇叭单元（5-15元一个）、锂电池（从旧手机/充电宝里拆或者单买10元）、充电保护板（5元）。外壳：可以用木质盒子、亚克力盒子、甚至一个竹筒。工具：电烙铁（30块）、焊锡丝、热熔胶枪（15块）。总成本50-80元。不用电烙铁也行——现在的功放板都是接线端子，螺丝刀就能搞定。'},{title:'🎵 组装流程',body:'1.先把功放板和喇叭、电池、充电板按说明书接好——就几根线，红接红黑接黑。2.上电测试——手机蓝牙搜到就连上放首歌听听。3.在外壳上开孔——喇叭口+充电口。4.热熔胶把所有零件固定好。5.合上外壳。全程1-2小时就能搞定。做出来的音箱低音肯定不如品牌的但中高频很清晰，送朋友当礼物超有面子。'},{title:'🔧 升级玩法',body:'喇叭升级（换个好点的喇叭单元音质提升最明显）、外壳升级（实木盒子比塑料的好看+音质好）、电池升级（换大容量电池续航10小时+）。很多人从做第一个蓝牙音箱开始入坑电子DIY最后成了硬件工程师。当然更可能的情况是——做了第一个觉得还有改进空间于是做了第二个第三个…停不下来了。'}]},
{title:'手搓一个手机无线充电器：超简单DIY，50元搞定',tag:'电子DIY',intro:'无线充电器原理其实超简单——一个线圈产生电磁场，另一个线圈接收。淘宝买个无线充电模块，加个外壳就搞定了。不需要任何电子基础。',sections:[{title:'🔧 材料清单',body:'无线充电发射模块（淘宝搜\"Qi无线充电模块\"15-25元）、USB-TypeC母座（3元）、外壳（可以是木盒子、亚克力盒子甚至一个好看的茶杯垫）。如果模块不带指示灯就自己加一个LED灯珠+电阻，用来显示充电状态。总成本不超过50元。买模块的时候看好输出功率——5W够用，10W充电更快。'},{title:'⚡ 组装步骤',body:'1.把充电模块和TypeC母座用导线连好（模块说明书有接线图）。2.在外壳上开好TypeC口。3.测试：插上USB线→放上手机→看能不能充电。4.模块用热熔胶固定在外壳里。5.盖上盖子完工。线圈离外壳表面不超过3mm才能正常充电——外壳太厚会充不了。如果带手机壳太厚也可能充不了——不过这是所有无线充电器的通病不是你做的问题。'}]},
];
const idx=(new Date().getDate()-1)%articles.length,a=articles[idx];
feed.posts.unshift({slug,date:today,title:a.title,tag:a.tag,intro:a.intro,sections:a.sections});
feed.updated=today;fs.writeFileSync(path.join(__dirname,'..','feed.json'),JSON.stringify(feed,null,2));
const html=`<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${a.title} - 手搓万物</title><style>*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}:root{--bg:#fafafa;--card:#fff;--text:#1a1a2e;--t2:#555;--accent:#ea580c;--border:#e5e7eb;--r:12px}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans SC",sans-serif;background:var(--bg);color:var(--text);line-height:1.9;font-size:16px}.container{max-width:750px;margin:0 auto;padding:0 20px}header{background:linear-gradient(135deg,#ea580c,#f97316);color:#fff;padding:36px 0;margin-bottom:24px}header a{color:rgba(255,255,255,.85);text-decoration:none;font-size:.9rem}header h1{font-size:1.5rem;margin-top:8px;line-height:1.4}.post{background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:32px}.post .intro{font-size:1rem;color:var(--t2);margin-bottom:28px;padding-bottom:20px;border-bottom:1px solid var(--border)}.section{margin-bottom:24px}.section h3{font-size:1.05rem;margin-bottom:6px;color:var(--accent)}.section p{color:var(--t2);font-size:.92rem;line-height:1.9}footer{text-align:center;padding:24px;color:#999;font-size:.75rem}@media(max-width:600px){.post{padding:18px}}</style></head><body><header><div class="container"><a href="../index.html">← 首页</a><h1>${a.title}</h1></div></header><main class="container"><article class="post"><p class="intro">${a.intro}</p>${a.sections.map(s=>`<div class="section"><h3>${s.title}</h3><p>${s.body}</p></div>`).join('')}</article></main><footer><p>🛠 手搓万物 · 每日更新</p></footer></body></html>`;
fs.writeFileSync(path.join(__dirname,'..','posts',slug+'.html'),html);console.log('OK');
